### ISSUE TITLE
pvr.hts pixelation issues, run same channel w/ VLC perfect

### ISSUE THREAD

**Issue by highkick05** [kodi-pvr/pvr.hts#244]
Hi, on certain TP's I've noticed I have pixelation on certain SD and HD feeds.

I can't see it being issue with dish , cable, dvbs hardware, driver, tvheadend, oscam, or kodi

It looks to be problem with the client side (pvr.hts) reading the stream because I can use VLC anywhere on the network and view the channel 100% pixel free

**Comment by Jalle19** [comment]
It's probably tvheadend not parsing the stream correctly. Tvheadend needs to parse the stream only when using Kodi, all other methods of streaming leave the parsing to the client.

I suggest you open a bug report on tvheadend.org instead.

**Comment by highkick05** [comment]
So how come VLC runs tvheadend's so called problematic stream with absolutely no issues at all ?

**Comment by highkick05** [comment]
doesn't even break close to a sweat , 

I saw it VLC spitting on pvr.hts in fact while I was watching them both side by side. sooo

**Comment by Jalle19** [comment]
Because when you play stuff in VLC the video is not processed by tvheadend at all, while if you watch it in Kodi through the addon it does.

You can test this by recording the problematic channel and playing that recording in Kodi, that should work even though playing it live is not.

**Comment by highkick05** [comment]
so why does pvr.hts make tvheadend process the stream when it doesn't need to ?

**Comment by highkick05** [comment]
maybe you could copy acestream's linux binaries to play the streams lol

**Comment by Jalle19** [comment]
That's just how it works, it's the biggest reason why tvheadend has faster channel switching than most other addons.

**Comment by highkick05** [comment]
sounds good. bloody annoying , one issue after the next setting all this up, constantly head butting walls

Thanks man

**Comment by Jalle19** [comment]
Does it only happen on certain channels?

**Comment by highkick05** [comment]
yeah man, don't get it cos oscam saying nothing, tvheadend nothing in logs (apart from the same old start code errors, but it doesn't seem to mind a few of these most of the time ?)

then VLC runs it crisp picture perfect. even though it's been descrambled the same way lol

**Comment by Leatherface75** [comment]
Probably similar issue like issues i have with a few streams like the official BBC ones.
It works with pass profile as it should but when using htsp or transcode it stutters.
pvr.hts is supposed to support different profiles but seems it doesn't work anymore.
Only htsp seems to work with pvr.hts for now.

**Comment by highkick05** [comment]
@Leatherface75  it's no good for Kodi mah man.. this is supposed to work &work well.

I hate it when coders forget why they begin designing things for in the first place. For all the work they've done we might as well setup VLC as server & run IPTV Simple client & forget about all this mess, as it seems we're only submitting bug complaints so that one day they can release tvheadend as some big commercial software package. Not that it would, but developers need to remember what it's principle use is, stop with the additional features until it can do the main things well, I mean tvheadend is purely a backend as well, the pvr client should be one of the core bits of software and should do it's part. The issues I'm complaining about have obviously been around for quite some time

**Comment by Jalle19** [comment]
It works well already, it's just non-DVB streams that may be problematic. You're barking up the wrong tree though, you need to raise this issue on tvheadend.org.

**Comment by Leatherface75** [comment]
IPTV streams from TVheadend including BBC streams i have issues with works with IPTV Simple Client from TVheadend and the reason it works is that it uses pass profile and not htsp or any transcoding.

**Comment by highkick05** [comment]
@Leatherface75 I originally used IPTV Simple client for everything, not pvr.hts .

So @Jalle19 does tvheadend's htsp code need to improve to the client ? What things would you suggest I submit issue with ?

**Comment by Jalle19** [comment]
The pass profile has never worked with pvr.hts because it's not how it works. The only profiles that work are HTSP and transcode because they are the only ones where tvheadend does the demuxing.

If you want to preserve teletext subtitles you can try recording to Matroska.

@highkick05 you need to open a ticket in tvheadend.org explaining exactly how you have your IPTV configured, then submit logs from both Kodi and tvheadend. The easier it is for someone to reproduce the better, so try to find an example that does not involve geoblocking.

**Comment by highkick05** [comment]
yeah, it's not pure IPTV (remote) , it's stream relay to be more specific (local), there should not be a problem. This same stream relay issues is no problem w/combination of tvheadend & oscam -> it just pops up when the pvr.hts comes into the equation, nd I'm not sure why it's complaining about "start code" & then rendering stream pixelated. It's interpreting the stream as damaged

**Comment by Jalle19** [comment]
> yeah, it's not pure IPTV (remote) , it's stream relay to be more specific (local), there should not be a problem

That's precisely why it doesn't work. tvheadend is mainly designed for DVB streams, the fact that it nowadays can play pretty much anything by transcoding the input does not mean everything will work just as well.

**Comment by Leatherface75** [comment]
TVheadend plays every stream i added without problem so that's not the problem.
The problem is when TVheadend touch the stream with htsp or transcode then it cause problems.
Playing streams in Kodi with IPTV Simple Client, m3u file or in VLC from tvheadend server works perfectly without problems.

About Teletext i know it works with Matroska and is the setup i always have been using.
But streams that have problems i need to record with pass profile without touching anything.
Then pvr.hts plays the recording without problem.

**Comment by Jalle19** [comment]
> TVheadend plays every stream i added without problem so that's not the problem.

That's exactly what it does *not* do. When you play something with VLC or pvr.iptvsimple, tvheadend serves the stream over HTTP without parsing it. When you play it with Kodi, tvheadend parses and demuxes the stream and sends it over HTSP to Kodi. You will get the exact same playback issues in VLC too if you download and use the HTSP plugin for it.

> I don't see the reason why pvr.hts can't support pass profile like VLC, PVR Simple Client etc does and with that setup it works as it should.

This is because HTSP != HTTP. Almost half the addon would have to be rewritten and the HTSP protocol would require some changes for that to even be a possibility, so I doubt it's going to happen. The `pass` profile is fundamentally incompatible with HTSP clients like Kodi.

Focus on getting tvheadend fixed by reporting this issue to them instead.

**Comment by Leatherface75** [comment]
I have reported this issue already and no response from anyone about this there.
Still a client for tvheadend should support pass profile and not only htsp or transcoding.
And why does recordings with pass profile work with pvr.hts but not live stream?

**Comment by highkick05** [comment]
We can all admit the benefits of htsp, I think we stick to this it's a good idea.

Maybe a better idea if we go different route & request oscam support PowerVU naturally without tvheadend needing to serve it twice. It does this already on dreambox's doesn't it ?

Is this the only problem you have @Leatherface75  ? or soemthing else other than problem regards stream_relay w/ htsp

**Comment by Leatherface75** [comment]
Except for a few streams with htsp/transcode everything works as it should for me.

**Comment by Jalle19** [comment]
Can you link the tvheadend ticket here?

**Comment by Leatherface75** [comment]
https://www.tvheadend.org/issues/3918
