### ISSUE TITLE
http://edgeb.streaming.sk/tvrlive/tvr1/f1tv.m3u8 fails to play

### ISSUE THREAD

**Issue by radoslavv** [kodi-pvr/pvr.hts#338]
1) Let's have a file /home/kodi/TV/TV_Ruzinov.m3u:
=========== Content ===========
#EXTM3U
#EXTINF:0,TV Ruzinov
http://edgeb.streaming.sk/tvrlive/tvr1/f1tv.m3u8
=========== Content ===========
2) Let's load m3u file via Configuration->DVB Inputs->Networks->Add, where Type=Automatic Network, and where in an URL field is inserted: file:///home/kodi/TV/TV_Ruzinov.m3u
3) Stream is successfully verified and everything is configured automatically and correctly on tabs:
Configuration->DVB Inputs->Muxes
Configuration->DVB Inputs->Services
Configuration->Channel/EPG->Channels
4) KODI shows channel in TV list
5) Trying to play stream via KODI fails, nothing is played

**Comment by Jalle19** [comment]
That is most likely a problem with tvheadend, not with this addon.

**Comment by radoslavv** [comment]
Hi,
I do not think so, because I am able to play stream via VLC through TVheadend (stream link is something like http://192.168.1.21:9981/play/stream/channel/808446e9b3be78848bdeb02ca3f45a2b?title=127%20%3A%20TV%20Ru%C5%BEinov).
So it must be something with HTSP plugin.
Check it, pls. You can try it yourself.

**Comment by Jalle19** [comment]
That doesn't mean it's not a tvheadend issue. HTSP doesn't support everything that HTTP does. There are other similar closed issues here.

**Comment by radoslavv** [comment]
Sorry, you are wrong.

Simple proof:
1) I took this m3u file
=========== Content ===========
#EXTM3U
#EXTINF:0,TV Ruzinov - direct
http://edgeb.streaming.sk/tvrlive/tvr1/f1tv.m3u8
#EXTINF:0,TV Ruzinov - tvheadend
http://192.168.1.21:9981/stream/channelid/1766229120?ticket=A0751669B0731EEBFA8A3C185FCC89699D377463&profile=pass
=========== Content ===========
2) in KODI i passed this m3u file through **PVR IPTV Simple Plugin**
3) both channels are played without problems.

=> YOU are wrong about tvheadend issue, it is Tvheadend HTSP Client bug.
If you still insist that not: prove, not just claim.

**Comment by Jalle19** [comment]
Unlike you I know what I'm talking about.

Tvheadend has two modes of operation - HTTP and HTSP. The method you've used to "prove" I am wrong is the HTTP method. When you stream something over HTTP, tvheadend basically just passes whatever comes from your input to the output.

However, when you stream over HTSP, which this addon does, tvheadend parses the stream packets and sends them in a completely different way. The video and audio formats it can parse is mostly limited to those that are used by actual DVB streams. This means that random streams you have happened to find on the Internet may not necessarily work.

Since this addon just takes whatever tvheadend sends and gives that to Kodi to play, there's nothing that can be done. You're barking up the wrong tree.

Like I said, there are a few very similar closed issues on this issue tracker, if you would have read them I wouldn't have had to explain all this yet again.

**Comment by radoslavv** [comment]
Hmm,
Found windows app [TVHPlayer Beta](https://www.microsoft.com/sk-sk/store/p/tvhplayer-beta/9nblggh5k12j?rtc=1) player for HTPS streams. Unfortunately no other windows apps to try.
There also does not work TV Ruzinov stream.
Did you reported this issue to tvheadend team? -> I can join next failing stream to same BUG.
Are you able to show some error message in HTSP client that stream is failing due to tvheadend server (or something like that)? This will avoid such a BUGs opening... Consider.
Greets Rado

**Comment by Jalle19** [comment]
I don't think it's possible to detect failures like that in addon, hence it's not possible for us to display a separate error message.

I haven't opened any tickets because I haven't been the one having issues. You can probably find something on the issue tracker if you browse back a few pages. If you can't find anything just open a new issue.

**Comment by ckarrie** [comment]
Seems to be fixed here: https://tvheadend.org/issues/4662#change-23848

**Comment by radoslavv** [comment]
Not completely fixed: https://tvheadend.org/issues/4662#change-23872
