### ISSUE TITLE
Feature request: add support for profile selection

### ISSUE THREAD

**Issue by TheTroll** [kodi-pvr/pvr.hts#40]
Hi,

it would be very nice to allow to select the streaming profile.
TVheadend exports the list of profiles that can be used...

Thanks!

**Comment by Jalle19** [comment]
I'm not really sure how to do it since the addon settings have to be static, aka. there's no communication with the backend before the addon is started. This means there's no way to retrieve the list of profiles at this point. It may be solvable using "client-specific settings", but I've never used that and I'm not even sure if it's possible to use those in a skin-independent matter.

**Comment by Jalle19** [comment]
Furthermore, I don't really think the client should be the one deciding which streaming profile should be used. Is there really a use case where you'd want to change the profile more than once? If not then I don't see why you couldn't specify the profile to use from the web interface.

**Comment by TheTroll** [comment]
Thanks for your answer!

My goal is to reduce the number of usernames for a single user.
I use kodi at home on my TV but also on my ipad.

On my TV I want the PASS profile and on my ipad a transcoding one...

It would be really great if I could avoid to duplicate usernames (i mean a user called "blah" and user called "transcoding-blah")

Thanks!

**Comment by Jalle19** [comment]
You can use the same username but different passwords, or limit the TV's user to the TV's IP address. The access entries are matched from top to bottom.

**Comment by TheTroll** [comment]
Indeed this is a possibility...
By the way I notice something very strange about that.
If I have a "user" with 2 lines.

- first line has  all access enable + the htsp profile selected
- second line has nothing enable + a transcoding profile selected

It is impossible to do a http streaming...
But if I invert the lines, it is ok and the PVR HTS client takes the HTSP profile

**Comment by Jalle19** [comment]
This is starting to be off-topic (join #hts on irc.freenode.net if you need general support) but that's probably because the first entry is only valid for HTSP, so when you try streaming over HTTP is falls back to the second entry which has no streaming permissions. You need to check "Streaming" in order to stream.

**Comment by TheTroll** [comment]
Yes sorry .. I ll check on irc
Thanks

**Comment by Jalle19** [comment]
@ksooo as discussed on IRC, what's your opinion on this: add a string setting to the addon where the user can enter the name of the streaming profile to use. If the profile exists, use it, otherwise don't. That way we don't need any user interface hacks.

**Comment by TheTroll** [comment]
I think it's a very good alternative!

**Comment by ksooo** [comment]
Not nice, because the string can't be validated after it was entered into the settings, but in general it should work, if the idea is to pass that string as parameter to htsp subscribe method (after checking validity of the profile via htsp getProfiles method). 

BTW, how is transcoding handled for playing recordings via htsp? Cannot find anything related in htsp spec.

**Comment by ksooo** [comment]
Perhaps we should inform the user if the runtime validation of the transcoding profile string fails. ;-)

**Comment by TheTroll** [comment]
Hi, yes would be nice :)
Well, all mpeg-ts transcoding work with HTSP, even with  hevc ones :)

**Comment by Jalle19** [comment]
@ksooo I agree it's not ideal, but it's better than nothing and should be very easy to implement. Naturally an invalid profile would be logged as an error.

**Comment by alexfd** [comment]
@TheTroll but why is it an inconvenience to have multiple usernames? Setting up your ipad / tv is generally a one time process, once you've done it you won't be touching it again anytime soon, no?

Also, is this documented anywhere? AFAIK assigning the streaming profile is something the backend does, not the frontend.

**Comment by TheTroll** [comment]
Hi,

well, if you want a user to have access to high,medium and low bitrates, depeding on its location, having 3 logins pr user is a nightmare, when you have 20 or 30 of them for instance.
TVH now allows to select multiple streaming profiles per user, add ?profile=name allows you to select it...

So it would be a great feature, at least in my view.

**Comment by bluenote73** [comment]
having multiple usernames breaks recording partitioning so this is a great addition IMO
