### ISSUE TITLE
Stuck at PMT switching

### ISSUE THREAD

**Issue by multiple1** [kodi-pvr/pvr.hts#494]
> Detecting PMT switches and signalling those to video player is responsibility of the demuxer. In case of hts protocol this is pvr.hts. It is a confirmed bug and should not be closed.

Can anyone reopen this issue as there is only a workaround?
And the workaround using http streaming also freezes for some seconds but it does not get stuck.
How to debug this further?

_Originally posted by @multiple1 in https://github.com/kodi-pvr/pvr.hts/issues/439#issuecomment-777362487_

**Comment by ksooo** [comment]
I fear this has to be fixed in tvheadend's demuxer. Nothing that the pvr.hts addon can do about.

**Comment by multiple1** [comment]
Are you sure that the issue is caused by tvheadend?
It exists for years and nobody has this issue?
Tried the stable 4.2 release and the 4.3 both have the same issue.

**Comment by Jalle19** [comment]
Everyonr has the issue, no one cares. I see this maybe once a month, and it has never ended in a permanent freeze. 🤷

**Comment by multiple1** [comment]
Sad story...

**Comment by ksooo** [comment]
@multiple1 yes, sad. And it's not we don't want to help. Problem is that currently nobody here seems to be able and/or willing to fix this. Speaking for myself, I have no clue how the demuxer works. All I can see is that the addon gets pakets from tvheadend and stores them (without modifying them)  until kodi reads them. So, my guess is that this is something that needs to be fixed in tvheadend.
