### ISSUE TITLE
Kodi crashing when accessing pvr.hts

### ISSUE THREAD

**Issue by cookieisland** [kodi-pvr/pvr.hts#532]
I have a situation where Kodi regularly crashes on startup when accessing TVheadend. This only happens when I have a Autorec set up in TVheadend.  I have posted more details on the CoreELEC forum but was hoping that the pvr.hts community may be able to help me.  I am using CoreElec (Kodi 19) on both an Odroid N2 and an Odroid N2+.

Here is my full post with details including crash log.

https://discourse.coreelec.org/t/tvheadend-client-pvr-hts-causing-kodi-system-crashes/16630

**Comment by ksooo** [comment]
Does it make a difference if you disable (or deinstall) pvr.iptvsimple, which it seems you are using in parallel ?

**Comment by ksooo** [comment]
And please supply a log with PVR component debugging enabled, thanks.

**Comment by cookieisland** [comment]
When I disable pvr.iptvsimple then pvr.hts works and kodi does not crash. as soon as I enable it again I get the crashes when Kodi starts up.  Here is a crash log with PVR component debugging enabled and pvr.iptvsimple enabled.

http://ix.io/3xmg

BTW: I have pvr.iptvsimple installed/enabled due to using some of Lunatiz's add ons like Newson, plutotv, etc. When I installed those addons they needed pvr.iptvsimple so it got installed as well.

**Comment by ksooo** [comment]
I think I know what happens. It's a combination of using two pvr add-ons, one with async connect implemented, the other without async connect, plus video and music scan running on startup. But only, if your EPG data provide series links. And it is a logical race condition. Quite a complex scenario and it took me a while to understand what's going wrong.

Anyway, this is something that needs to be fixed in Kodi, not the add-on. I will be happy to come up with a fix. So, could you please open an issue over at github.com/xbmc and close this issue here?

**Comment by cookieisland** [comment]
Thank you! Per your request I opened an issue with Kodi and will close this issue.  Here is the issue I just opened:

https://github.com/xbmc/xbmc/issues/20090
